- name: Configure Nginx server with reverse proxy
  hosts: aws_servers
  become: true
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx service is enabled and started
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Ensure sites-available directory exists
      file:
        path: /etc/nginx/sites-available
        state: directory

    - name: Create reverse proxy configuration file if it doesn't exist
      file:
        path: /etc/nginx/sites-available/reverse-proxy
        state: touch

    - name: Append block to reverse proxy configuration file
      blockinfile:
        path: /etc/nginx/sites-available/reverse-proxy
        block: |
          server {
              listen 80;
              server_name localhost;
              location / {
                  proxy_pass http://internal-nti-lb2-1049882033.eu-west-3.elb.amazonaws.com:80;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
    - name: Create symlink for reverse proxy configuration
      file:
        src: /etc/nginx/sites-available/reverse-proxy
        dest: /etc/nginx/sites-enabled/reverse-proxy
        state: link